
DATA:
  NAME: mnist           # Now: mnist or fashion
  CLASS: 10             # number of class of mnist
  DATA_NUM: 100
  SPLIT_RATIO: 0.2

MODEL:
  INPUT_FEATURES: 784   # mnist: 28x28=784
  MID_FEATURES: 2048
  B_SIGMA: 0.1
  VISUALIZE: false      # usually false

INITIALIZER:
  TYPE: gaussian        # vanilla, gaussian, withmp, mexican, matern
  R_SIGMA: 0.1          # for receptive field
  S_SIGMA: 0.1          # for correlation
  M_SIGMA: 0.1          # for mexican hat
  NU: 0.5               # for matern kernel

GENERAL:
  EPOCH: 1000
  GPUS: [0]
  NOTEBOOK: true        # if you use script, switch false